# Generated by Django 4.1.4 on 2022-12-25 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Medicines",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("mg", models.IntegerField()),
                ("price", models.FloatField(null=True)),
                ("available", models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=200)),
                ("lastname", models.CharField(max_length=200, null=True)),
                ("username", models.CharField(max_length=200, unique=True)),
                ("password", models.CharField(max_length=200)),
                ("phonecode", models.CharField(max_length=10)),
                ("phNo", models.IntegerField(max_length=20)),
                ("email", models.CharField(max_length=200, unique=True)),
                ("houseNo", models.CharField(max_length=200)),
                ("area", models.CharField(max_length=200)),
                ("state", models.CharField(max_length=200)),
                ("city", models.CharField(max_length=200)),
                ("pincode", models.IntegerField(max_length=20)),
                ("requirement", models.CharField(max_length=200)),
            ],
        ),
    ]
