# Generated by Django 4.1.4 on 2022-12-25 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work", "0002_alter_user_phno_alter_user_pincode"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="id",),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                max_length=200, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
