# Generated by Django 4.1.4 on 2022-12-25 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work", "0003_remove_user_id_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
