# Generated by Django 4.0.1 on 2022-12-25 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0006_customer_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='username',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
