# Generated by Django 4.1.4 on 2022-12-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work", "0007_alter_customer_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="city",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="state",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
