# Generated by Django 4.1.4 on 2022-12-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work", "0008_alter_customer_city_alter_customer_state"),
    ]

    operations = [
        migrations.RemoveField(model_name="customer", name="id",),
        migrations.RemoveField(model_name="customer", name="user",),
        migrations.AlterField(
            model_name="customer",
            name="area",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="firstname",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="houseNo",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="password",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="customer", name="phNo", field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="customer", name="pincode", field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="requirement",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="username",
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
